pipeline {
    agent any

    environment {
        PYTHON = 'python'
    }

    stages {
        stage('Install Dependencies') {
            steps {
                echo 'Установка зависимостей...'
                bat "${PYTHON} -m pip install -r requirements.txt"
            }
        }

        stage('Get Data') {
            steps {
                echo 'Получение данных...'
                bat "${PYTHON} scripts/fetch_data.py"
            }
        }

        stage('Data Preprocessing') {
            steps {
                echo 'Предобработка данных...'
                bat "${PYTHON} scripts/preprocess.py"
            }
        }

        stage('Train Model') {
            steps {
                echo 'Обучение модели...'
                bat "${PYTHON} scripts/train.py"
            }
        }

        stage('Test Model') {
            steps {
                echo 'Оценка модели...'
                bat "${PYTHON} scripts/evaluate.py"
            }
        }
    }

    post {
        success {
            echo 'Все этапы Lab 2 выполнены успешно!'
        }
        failure {
            echo 'Произошла ошибка при выполнении конвейера Lab 2.'
        }
    }
}
